#include <stdlib.h>
#include <stdio.h>
void main (void)
{
	int vector [5], i=0, c=0;
	int max;
	char buff[20], buffer;
	for (i = 0; i < 5 ; i++)
	{
		printf("Ingresar numero entero\n");
		gets(buff);
		vector[i]=atoi (buff);
	}


	//muestra lo cargado
	for (i = 0; i < 5 ; i++)
	{
		printf("El numero es %d\n",vector[i]);
		getchar();
	}


	//ordenar
	max=vector[i];
	for (i=0;i<5;i++)
	{
	if (vector[i]>max){
	aux
	}

	}


}